# Generated by Django 5.0.4 on 2024-04-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OddData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('league_name', models.CharField(blank=True, max_length=64, null=True)),
                ('league_id', models.IntegerField()),
                ('home', models.CharField(blank=True, max_length=42, null=True)),
                ('away', models.CharField(blank=True, max_length=42, null=True)),
                ('date', models.DateField()),
                ('bookmaker', models.CharField(max_length=32)),
                ('home_od', models.FloatField()),
                ('away_od', models.FloatField()),
                ('od_add_time', models.DateTimeField()),
                ('stamp', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
